################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELFS := 
OBJS := 
ASM_DEPS := 
S_DEPS := 
SIZEDUMMY := 
S_UPPER_DEPS := 
LSS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
APP/MAIN \
HAL/BTN/BTN0 \
HAL/BTN/BTN1 \
HAL/BTN/BTN2 \
HAL/DISPLAY/LCD \
HAL/DISPLAY/SEVENSEGMENT \
HAL/EEPROM_24C16N \
HAL/IO/BUZZER \
HAL/IO/RELAY \
HAL/KEYPAD \
HAL/LED/LED0 \
HAL/LED/LED1 \
HAL/LED/LED2 \
HAL/MOTORS/DC \
HAL/MOTORS/SERVO \
HAL/MOTORS/STEPPER \
MCAL/ADC \
MCAL/COMMUNICATION/SPI \
MCAL/COMMUNICATION/TWI \
MCAL/COMMUNICATION/UART \
MCAL/DIO \
MCAL/EEPROM \
MCAL/Interrupts \
MCAL/TIMERS/TIMER0/CTC \
MCAL/TIMERS/TIMER0/OVF \
MCAL/TIMERS/TIMER0/PWM/FAST \
MCAL/TIMERS/TIMER1/CTC \
MCAL/TIMERS/TIMER1/OVF \
MCAL/TIMERS/TIMER2/CTC \
MCAL/TIMERS/TIMER2/OVF \
MCAL/TIMERS/TIMER2/PWM/FAST \
MCAL/TIMERS/WDT \
RTOS/API \
RTOS/Source \

