/*
* SEV_SEGMENT_Program.c
*
* Created: 1/26/2024 2:56:15 PM
*  Author: karim
*/
#include "../SEVENSEGMENT/SEV_SEGMENT_Interface.h"

void SEVENSEGMENT_Initialize(void)
{
	DIO_SetPinDirection(SEVSEG_DATA_PORT, SEVSEG_DATA_A, SEVSEG_OUTPUT);
	DIO_SetPinDirection(SEVSEG_DATA_PORT, SEVSEG_DATA_B, SEVSEG_OUTPUT);
	DIO_SetPinDirection(SEVSEG_DATA_PORT, SEVSEG_DATA_C, SEVSEG_OUTPUT);
	DIO_SetPinDirection(SEVSEG_DATA_PORT, SEVSEG_DATA_D, SEVSEG_OUTPUT);
	
	DIO_SetPinDirection(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_EN1, SEVSEG_OUTPUT);
	DIO_SetPinDirection(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_EN2, SEVSEG_OUTPUT);
	DIO_SetPinDirection(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_DIP, SEVSEG_OUTPUT);
}
void SEVENSEGMENT_Enable1(void)
{
	DIO_SetPinValue(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_EN1, SEVSEG_HIGH);
}
void SEVENSEGMENT_Disable1(void)
{
	DIO_SetPinValue(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_EN1, SEVSEG_LOW);
}
void SEVENSEGMENT_Enable2(void)
{
	DIO_SetPinValue(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_EN2, SEVSEG_HIGH);
}
void SEVENSEGMENT_Disable2(void)
{
	DIO_SetPinValue(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_EN2, SEVSEG_LOW);
}
void SEVENSEGMENT_DIP_Enable(void)
{
	DIO_SetPinValue(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_DIP, SEVSEG_HIGH);
}
void SEVENSEGMENT_DIP_Disable(void)
{
	DIO_SetPinValue(SEVSEG_CONTROL_PORT, SEVSEG_CONTROL_DIP, SEVSEG_LOW);
}
void SEVENSEGMENT_Display_Number(uint8_t number)
{
	uint8_t uint  = number%10;
	uint8_t tenth = number/10;
	SEVSEG_PORT = uint<<4;
	SEVENSEGMENT_Enable1();
	SEVENSEGMENT_Disable2();
	_delay_ms(10);
	SEVSEG_PORT = tenth<<4;
	SEVENSEGMENT_Disable1();
	SEVENSEGMENT_Enable2();
	_delay_ms(10);
}
